# Generated by Django 2.2.19 on 2021-04-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('date_start', models.DateTimeField(verbose_name='Start Date')),
                ('date_end', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
    ]
